### ISSUE TITLE
backslash don't work

### ISSUE THREAD

**Issue by xnousnow** [Kirilllive/ASCII_Art_Paint#2]
I cannot click the backlash even if i have `\` in the palette.

**Comment by xnousnow** [comment]
It works again!

**Comment by xnousnow** [comment]
Um, the backslash don't work still, but I can alternatively use similar character!

**Comment by Kirilllive** [comment]
Hello!
It is likely that the key with this symbol has a separate functionality in your browser. I can't reproduce this issue in FireFox or Chrome, I need more information to reproduce the issue.

**Comment by xnousnow** [comment]
1. Add `\` and `/` to the palette.
2. If `\` is already selected, select another character.
3. You can't select the `\` character.

**Comment by Kirilllive** [comment]
It turned out to repeat the problem
She's already fixed
