### ISSUE TITLE
Something wrong with   ͞  character

### ISSUE THREAD

**Issue by systemdfan** [Kirilllive/ASCII_Art_Paint#5]
Hello everyone! Sorry for dumb questions, I'm not an expert in ascii and other encoding and character things. But I found something strange happening with   ͞   character
![image](https://github.com/Kirilllive/ASCII_Art_Paint/assets/81460388/9b95daf7-5aed-401a-a604-d89914e95b42)
this is how my ascii art looks with courner new font in ASCII art paint.

![image](https://github.com/Kirilllive/ASCII_Art_Paint/assets/81460388/58d7f636-e950-450e-b5aa-bf177b3b2574)
This is how it looks in text input mode.

![image](https://github.com/Kirilllive/ASCII_Art_Paint/assets/81460388/59c81ed0-2303-4eb7-a021-8a1e4685374a)
And this is how it looks in .html file opened in notepad++ 

This symbol is somehow strangely crumpled, and in different ways in different editors. Just look at the top of her head on these 3 screenshots.
Can someone please tell me what's the matter? Is this a bug or a feature?
Text file with picture is [text_art.5.txt](https://github.com/Kirilllive/ASCII_Art_Paint/files/15016460/text_art.5.txt)

**Comment by Kirilllive** [comment]
I think this is the specificity of displaying symbols overlapping with another symbol that you used ( ̶̶̲̲̲͞͞͞͞͞͞͞͞ ) 
try using others instead ( _ - ¯ )

**Comment by systemdfan** [comment]
Yes, it is possible. Most likely it is. Thanks, I'll keep that in mind.

**Comment by systemdfan** [comment]
Yes, it is possible. Most likely it is. Thanks, I'll keep that in mind.
